# Generated by Django 4.2.2 on 2023-06-16 00:21

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option3', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option4', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ans', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.testgroup')),
            ],
        ),
    ]
