# Generated by Django 4.2.2 on 2023-06-17 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0002_testgroup_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='test_app.testgroup'),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
