# Generated by Django 4.2.2 on 2023-06-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_test_test_group_alter_testgroup_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='ans',
            new_name='answer',
        ),
    ]
